#!/bin/bash

#####
# 1. deploys code to live
#####

SERVERPORT="2520"

ERRORSTRING="Whoops! That didn't work. Please check the command you ran."
if [ $# -eq 0 ]
then
  echo "$ERRORSTRING";

elif [[ "$1" == "math" ]]
then
  if [[ -z $2 ]]
  then
    echo "Staging Deploy: DRY RUN"
    rsync --dry-run --itemize-changes --force --recursive --ignore-times --group --owner --checksum --compress --delete --progress --exclude-from=.rsyncignore ./ hatfieldbros@deploy.us1.frbit.com:~/math/
  elif [[ "$2" == "go" ]]
  then
    echo "Live Deploy: REAL"
    rsync --itemize-changes --force --recursive --ignore-times --group --owner --checksum --compress --delete --progress --exclude-from=.rsyncignore ./ hatfieldbros@deploy.us1.frbit.com:~/math/
  else
    echo "$ERRORSTRING";
  fi

fi
